// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChat = "chats"

// Chat mapped from table <chats>
type Chat struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	User1ID   int32     `gorm:"column:user1_id" json:"user1_id"`
	User2ID   int32     `gorm:"column:user2_id" json:"user2_id"`
	CreatedAt time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName Chat's table name
func (*Chat) TableName() string {
	return TableNameChat
}
