// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChatMember = "chat_members"

// ChatMember mapped from table <chat_members>
type ChatMember struct {
	ID       int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ChatID   int32     `gorm:"column:chat_id" json:"chat_id"`
	UserID   int32     `gorm:"column:user_id" json:"user_id"`
	JoinedAt time.Time `gorm:"column:joined_at;default:now()" json:"joined_at"`
}

// TableName ChatMember's table name
func (*ChatMember) TableName() string {
	return TableNameChatMember
}
