// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessage = "messages"

// Message mapped from table <messages>
type Message struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int32     `gorm:"column:user_id" json:"user_id"`
	Content   string    `gorm:"column:content;not null" json:"content"`
	CreatedAt time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	Length    int32     `gorm:"column:length" json:"length"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
