// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransaction = "transactions"

// Transaction mapped from table <transactions>
type Transaction struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      int32     `gorm:"column:user_id" json:"user_id"`
	Type        string    `gorm:"column:type;not null" json:"type"`
	Amount      int32     `gorm:"column:amount;not null" json:"amount"`
	CreatedAt   time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	Description string    `gorm:"column:description" json:"description"`
}

// TableName Transaction's table name
func (*Transaction) TableName() string {
	return TableNameTransaction
}
