// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newChatMember(db *gorm.DB, opts ...gen.DOOption) chatMember {
	_chatMember := chatMember{}

	_chatMember.chatMemberDo.UseDB(db, opts...)
	_chatMember.chatMemberDo.UseModel(&model.ChatMember{})

	tableName := _chatMember.chatMemberDo.TableName()
	_chatMember.ALL = field.NewAsterisk(tableName)
	_chatMember.ID = field.NewInt32(tableName, "id")
	_chatMember.ChatID = field.NewInt32(tableName, "chat_id")
	_chatMember.UserID = field.NewInt32(tableName, "user_id")
	_chatMember.JoinedAt = field.NewTime(tableName, "joined_at")

	_chatMember.fillFieldMap()

	return _chatMember
}

type chatMember struct {
	chatMemberDo

	ALL      field.Asterisk
	ID       field.Int32
	ChatID   field.Int32
	UserID   field.Int32
	JoinedAt field.Time

	fieldMap map[string]field.Expr
}

func (c chatMember) Table(newTableName string) *chatMember {
	c.chatMemberDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chatMember) As(alias string) *chatMember {
	c.chatMemberDo.DO = *(c.chatMemberDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chatMember) updateTableName(table string) *chatMember {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.ChatID = field.NewInt32(table, "chat_id")
	c.UserID = field.NewInt32(table, "user_id")
	c.JoinedAt = field.NewTime(table, "joined_at")

	c.fillFieldMap()

	return c
}

func (c *chatMember) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chatMember) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 4)
	c.fieldMap["id"] = c.ID
	c.fieldMap["chat_id"] = c.ChatID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["joined_at"] = c.JoinedAt
}

func (c chatMember) clone(db *gorm.DB) chatMember {
	c.chatMemberDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chatMember) replaceDB(db *gorm.DB) chatMember {
	c.chatMemberDo.ReplaceDB(db)
	return c
}

type chatMemberDo struct{ gen.DO }

type IChatMemberDo interface {
	gen.SubQuery
	Debug() IChatMemberDo
	WithContext(ctx context.Context) IChatMemberDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IChatMemberDo
	WriteDB() IChatMemberDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IChatMemberDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IChatMemberDo
	Not(conds ...gen.Condition) IChatMemberDo
	Or(conds ...gen.Condition) IChatMemberDo
	Select(conds ...field.Expr) IChatMemberDo
	Where(conds ...gen.Condition) IChatMemberDo
	Order(conds ...field.Expr) IChatMemberDo
	Distinct(cols ...field.Expr) IChatMemberDo
	Omit(cols ...field.Expr) IChatMemberDo
	Join(table schema.Tabler, on ...field.Expr) IChatMemberDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IChatMemberDo
	RightJoin(table schema.Tabler, on ...field.Expr) IChatMemberDo
	Group(cols ...field.Expr) IChatMemberDo
	Having(conds ...gen.Condition) IChatMemberDo
	Limit(limit int) IChatMemberDo
	Offset(offset int) IChatMemberDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IChatMemberDo
	Unscoped() IChatMemberDo
	Create(values ...*model.ChatMember) error
	CreateInBatches(values []*model.ChatMember, batchSize int) error
	Save(values ...*model.ChatMember) error
	First() (*model.ChatMember, error)
	Take() (*model.ChatMember, error)
	Last() (*model.ChatMember, error)
	Find() ([]*model.ChatMember, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChatMember, err error)
	FindInBatches(result *[]*model.ChatMember, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ChatMember) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IChatMemberDo
	Assign(attrs ...field.AssignExpr) IChatMemberDo
	Joins(fields ...field.RelationField) IChatMemberDo
	Preload(fields ...field.RelationField) IChatMemberDo
	FirstOrInit() (*model.ChatMember, error)
	FirstOrCreate() (*model.ChatMember, error)
	FindByPage(offset int, limit int) (result []*model.ChatMember, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IChatMemberDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c chatMemberDo) Debug() IChatMemberDo {
	return c.withDO(c.DO.Debug())
}

func (c chatMemberDo) WithContext(ctx context.Context) IChatMemberDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c chatMemberDo) ReadDB() IChatMemberDo {
	return c.Clauses(dbresolver.Read)
}

func (c chatMemberDo) WriteDB() IChatMemberDo {
	return c.Clauses(dbresolver.Write)
}

func (c chatMemberDo) Session(config *gorm.Session) IChatMemberDo {
	return c.withDO(c.DO.Session(config))
}

func (c chatMemberDo) Clauses(conds ...clause.Expression) IChatMemberDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c chatMemberDo) Returning(value interface{}, columns ...string) IChatMemberDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c chatMemberDo) Not(conds ...gen.Condition) IChatMemberDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c chatMemberDo) Or(conds ...gen.Condition) IChatMemberDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c chatMemberDo) Select(conds ...field.Expr) IChatMemberDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c chatMemberDo) Where(conds ...gen.Condition) IChatMemberDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c chatMemberDo) Order(conds ...field.Expr) IChatMemberDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c chatMemberDo) Distinct(cols ...field.Expr) IChatMemberDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c chatMemberDo) Omit(cols ...field.Expr) IChatMemberDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c chatMemberDo) Join(table schema.Tabler, on ...field.Expr) IChatMemberDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c chatMemberDo) LeftJoin(table schema.Tabler, on ...field.Expr) IChatMemberDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c chatMemberDo) RightJoin(table schema.Tabler, on ...field.Expr) IChatMemberDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c chatMemberDo) Group(cols ...field.Expr) IChatMemberDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c chatMemberDo) Having(conds ...gen.Condition) IChatMemberDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c chatMemberDo) Limit(limit int) IChatMemberDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c chatMemberDo) Offset(offset int) IChatMemberDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c chatMemberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IChatMemberDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c chatMemberDo) Unscoped() IChatMemberDo {
	return c.withDO(c.DO.Unscoped())
}

func (c chatMemberDo) Create(values ...*model.ChatMember) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c chatMemberDo) CreateInBatches(values []*model.ChatMember, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c chatMemberDo) Save(values ...*model.ChatMember) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c chatMemberDo) First() (*model.ChatMember, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChatMember), nil
	}
}

func (c chatMemberDo) Take() (*model.ChatMember, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChatMember), nil
	}
}

func (c chatMemberDo) Last() (*model.ChatMember, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChatMember), nil
	}
}

func (c chatMemberDo) Find() ([]*model.ChatMember, error) {
	result, err := c.DO.Find()
	return result.([]*model.ChatMember), err
}

func (c chatMemberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChatMember, err error) {
	buf := make([]*model.ChatMember, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c chatMemberDo) FindInBatches(result *[]*model.ChatMember, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c chatMemberDo) Attrs(attrs ...field.AssignExpr) IChatMemberDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c chatMemberDo) Assign(attrs ...field.AssignExpr) IChatMemberDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c chatMemberDo) Joins(fields ...field.RelationField) IChatMemberDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c chatMemberDo) Preload(fields ...field.RelationField) IChatMemberDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c chatMemberDo) FirstOrInit() (*model.ChatMember, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChatMember), nil
	}
}

func (c chatMemberDo) FirstOrCreate() (*model.ChatMember, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChatMember), nil
	}
}

func (c chatMemberDo) FindByPage(offset int, limit int) (result []*model.ChatMember, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c chatMemberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c chatMemberDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c chatMemberDo) Delete(models ...*model.ChatMember) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *chatMemberDo) withDO(do gen.Dao) *chatMemberDo {
	c.DO = *do.(*gen.DO)
	return c
}
