// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q           = new(Query)
	Chat        *chat
	ChatMember  *chatMember
	Message     *message
	Transaction *transaction
	User        *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Chat = &Q.Chat
	ChatMember = &Q.ChatMember
	Message = &Q.Message
	Transaction = &Q.Transaction
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		Chat:        newChat(db, opts...),
		ChatMember:  newChatMember(db, opts...),
		Message:     newMessage(db, opts...),
		Transaction: newTransaction(db, opts...),
		User:        newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Chat        chat
	ChatMember  chatMember
	Message     message
	Transaction transaction
	User        user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Chat:        q.Chat.clone(db),
		ChatMember:  q.ChatMember.clone(db),
		Message:     q.Message.clone(db),
		Transaction: q.Transaction.clone(db),
		User:        q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Chat:        q.Chat.replaceDB(db),
		ChatMember:  q.ChatMember.replaceDB(db),
		Message:     q.Message.replaceDB(db),
		Transaction: q.Transaction.replaceDB(db),
		User:        q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Chat        IChatDo
	ChatMember  IChatMemberDo
	Message     IMessageDo
	Transaction ITransactionDo
	User        IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Chat:        q.Chat.WithContext(ctx),
		ChatMember:  q.ChatMember.WithContext(ctx),
		Message:     q.Message.WithContext(ctx),
		Transaction: q.Transaction.WithContext(ctx),
		User:        q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
